# MoveIt uses this to find the ros2_control controllers
moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - BaseRotate_0
      - UpperArmRotate_0
      - ForeArmRotate_0
      - WristRotate_0
      - PaddleRotate_0